name: lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          check-latest: true
      - run: npm install
      
      - uses: actions/checkout@v2
      - name: Install lint
        run: npm install
      
      - name: Run eslint
        run: make lint
 
      - name: Test & publish code coverage
        # Publish code coverage on Code Climate
        # https://github.com/paambaati/codeclimate-action
        uses: paambaati/codeclimate-action@v2.7.4
        # Add Code Climate secret key
        env:
          CODECLIMATE_ID: ${{ secrets.CODECLIMATE_ID }}
        with:
          coverageCommand: make test-coverage
          debug: true
